/**
 * 使用方法
 *   所有的lua技能和modifier在使用@registerAbility和@registerModifier
 *   时如果有提供参数，会被自动添加
 * 
 *   你也可以使用 InlineLocalizationManager.AddToken来添加任意字段
 *   
 *   在进入pre-game和post-game的时候，token会被自动保存
 *   也可以在控制台输入 x_local 指令来手动保存
 * 
 * Usage
 *   lua abilities and modifiers will be auto generated by
 *   @registerAbility and @registerModifier parameters
 *   
 *   data will be auto-saved when entering pre-game or post-game
 *   you can also use x_local command to manually save it
 * 
 *   tokens is saved to 
 *   localization/[path according to language set in pakcage.json]/inline_localization.txt
 *   and auto-compiled to resource/addon_lang.txt by scripts/localization.js
 *   
 *   you can also use InlineLocalizationManager.AddToken(string, string)
 *   to add any tokens
 * 
 */

declare interface json {
    encode(value: any): string;
    decode(json_string: string): object;
}

declare global {
    interface InlineLocalizationManager {
        AddToken(key: string, value: string): void;
    }
}

// require the dkjson module provided by valve
if (json == null) { require('game/dkjson'); }

export class InlineLocalizationManager {
    private static inited: boolean;
    public static tokens: Record<string, string> = {};
    public static AddLuaAbility(name: string, localizationDef: { Name: string, Tokens: { [x: string]: string; }; }) {
        if (!IsInToolsMode()) return;
        if (!this.inited) this.Initialize();
        this.tokens[`dota_tooltip_ability_${name}`] = localizationDef.Name;
        for (let key in localizationDef.Tokens) {
            this.tokens[`dota_tooltip_ability_${name}_${key}`] = localizationDef.Tokens[key];
        }
    }
    public static AddLuaModifier(name: string, localizationDef: { Name: string, Description: string; }) {
        if (!IsInToolsMode()) return;
        if (!this.inited) this.Initialize();
        this.tokens[`dota_tooltip_modifier_${name}`] = localizationDef.Name;
        this.tokens[`dota_tooltip_modifier_${name}_description`] = localizationDef.Description;
    }
    public static AddToken(key: string, value: string) {
        if (!IsInToolsMode()) return;
        if (!this.inited) this.Initialize();
        this.tokens[key] = value;
    }
    public static SendSaveRequestToDevServer() {
        if (!IsInToolsMode()) return;
        // send request to dev server
        print("sending save request to dev server ===>");
        DeepPrintTable(this.tokens);
        let req = CreateHTTPRequestScriptVM('POST', 'http://127.0.0.1:62323/Localization');
        req.SetHTTPRequestGetOrPostParameter('data', json.encode(this.tokens));
        req.Send(() => {
            print("inline localization job's done!");
        });
    }
    private static Initialize() {
        // listen to game state changed event
        // send game event at game start and game ends
        // register a console command to manually call
        Convars.RegisterCommand('x_local', () => { this.SendSaveRequestToDevServer(); }, 'send inline localization data to dev server', ConVarFlags.FCVAR_NONE);
        ListenToGameEvent("dota_game_state_change", () => {
            let state = GameRules.State_Get();
            if (state == DOTA_GameState.DOTA_GAMERULES_STATE_PRE_GAME || state == DOTA_GameState.DOTA_GAMERULES_STATE_POST_GAME) {
                this.SendSaveRequestToDevServer();
            }
        }, undefined);
    }
}
